# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on: push

jobs:
  open-ports-check-action:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos, windows]
        needFail: ['true', 'false']
        reverse: ['true', 'false']
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: nrukavkov/open-ports-check-action@v1
        with:
          port: 80, 443
          pause: 1000
          host: 'google.com'
          needFail: ${{ matrix.needFail }}
          reverse: ${{ matrix.reverse }}
